global:
  namespace: staging

services:
  api-gateway:
    image:
      tag: latest
    ingress:
      host: petclinic-staging.com

  admin-server:
    image:
      tag: latest

  config-server:
    image:
      tag: latest

  customers-service:
    image:
      tag: latest

  discovery-server:
    image:
      tag: latest
    
  vets-service:
    image:
      tag: latest

  visits-service:
    image:
      tag: latest

  genai-service:
    image:
      tag: latest
