global:
  namespace: staging
  dockeruser: minhhuy27

imageTag: &tag V7.0

services:
  api-gateway:
    type: LoadBalancer
    image:
      tag: *tag
      

  config-server:
    image:
      tag: *tag

  discovery-server:
    image:
      tag: *tag

  customers-service:
    image:
      tag: *tag
    
  vets-service:
    image:
      tag: *tag

  visits-service:
    image:
      tag: *tag

