apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-petclinic-dev
  namespace: argocd
spec:
  project: default
  
  source: 
    repoURL: https://github.com/22120137/project02-k8s.git
    targetRevision: HEAD
    path: .
    helm:
      valueFiles:
      - values.yaml
      - environments/dev-review/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dev-review
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true