apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}-ingress
  namespace: {{ $.Values.global.namespace }}
spec:
  rules:
  - host: {{ $host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $name }}
            port:
              number: {{ $port }}
{{- end }}
{{- end }}