global:
  namespace: tlavu-petclinic-dev-review
  ingress:
    enabled: false

services:
  spring-petclinic-admin-server:
    enabled: true
    name: admin-server
    image: tlavu2004/spring-petclinic-admin-server
    tag: latest
    port: 9090
    nodePort: 31090
    replicaCount: 1

  spring-petclinic-api-gateway:
    enabled: true
    name: api-gateway
    image: tlavu2004/spring-petclinic-api-gateway
    tag: latest
    port: 8080
    nodePort: 31070
    replicaCount: 1

  spring-petclinic-config-server:
    enabled: true
    name: config-server
    image: tlavu2004/spring-petclinic-config-server
    tag: latest
    port: 8888
    nodePort: 31088
    replicaCount: 1

  spring-petclinic-customers-service:
    enabled: true
    name: customers-service
    image: tlavu2004/spring-petclinic-customers-service
    tag: latest
    port: 8081
    nodePort: 31082
    replicaCount: 1

  spring-petclinic-discovery-server:
    enabled: true
    name: discovery-server
    image: tlavu2004/spring-petclinic-discovery-server
    tag: latest
    port: 8761
    nodePort: 31076
    replicaCount: 1

  spring-petclinic-genai-service:
    enabled: true
    name: genai-service
    image: tlavu2004/spring-petclinic-genai-service
    tag: latest
    port: 8080
    nodePort: 31083
    replicaCount: 1

  spring-petclinic-vets-service:
    enabled: true
    name: vets-service
    image: tlavu2004/spring-petclinic-vets-service
    tag: latest
    port: 8083
    nodePort: 31080
    replicaCount: 1

  spring-petclinic-visits-service:
    enabled: true
    name: visits-service
    image: tlavu2004/spring-petclinic-visits-service
    tag: latest
    port: 8082
    nodePort: 31081
    replicaCount: 1
