global:
  namespace: dev-review

services:
  api-gateway:
    image:
      tag: latest

  config-server:
    image:
      tag: latest

  discovery-server:
    image:
      tag: latest

  customers-service:
    image:
      tag: latest
    
  vets-service:
    image:
      tag: latest

  visits-service:
    image:
      tag: latest

  
