apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
  namespace: dev-review
  labels:
    app: prometheus
data:
  alert_rules.yml: |
    groups:
      - name: petclinic-alerts
        rules:
          - alert: HighErrorRate
            expr: |
              sum(rate(http_server_requests_seconds_count{status=~"5.."}[30s])) > 10
            for: 30s
            labels:
              severity: critical
            annotations:
              summary: "High 5xx error rate detected"
              description: "More than 10 5xx errors in 30s."
