global:
  namespace: dev

services:
  api-gateway:
    image:
      tag: 3ed9ef1
    ingress:
      host: petclinic-dev-review.com

  config-server:
    image:
      tag: latest

  discovery-server:
    image:
      tag: latest

  customers-service:
    image:
      tag: latest
    
  vets-service:
    image:
      tag: latest

  visits-service:
    image:
      tag: latest

  
