global:
  namespace: dev

services:
  api-gateway:
    image:
      tag: 3a691d1
    ingress:
      host: petclinic-dev.com

  config-server:
    image:
      tag: 9aec9de

  discovery-server:
    image:
      tag: 3a691d1

  customers-service:
    image:
      tag: 3a691d1
    
  vets-service:
    image:
      tag: 3a691d1

  visits-service:
    image:
      tag: 3a691d1

  
